settings:
  headless: true
  timeout: 45000
  wait_after_load: 3000
  failure_threshold: 3
  only_notify_found: true

targets:
  - id: hells_nether_deck
    name: "Hells Nether Deck Set"
    url: "https://lastchancetoy.com/collections/beybladex"
    method: "requests"
    value: "UX-21"
    #must_have:
    # - "UX-21"
    #must_not_have:
      #- "售完"
      #- "售罄"
