settings:
  headless: true
  timeout: 45000
  wait_after_load: 3000
  failure_threshold: 3
  only_notify_found: true

targets:
  - id: CX_11
    name: "帝皇霸權3陀螺套裝"
    url: "https://lastchancetoy.com/collections/beybladex"
    method: "requests"
    value: "CX-11"
    #must_have:
    # - "UX-21"
    #must_not_have:
      #- "售完"
      #- "售罄"
